# Generated by Django 2.2.3 on 2021-01-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=150)),
                ('imgPath', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Сategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('imgPath', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgPath', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=300)),
                ('mod', models.CharField(blank=True, max_length=150)),
                ('prise', models.CharField(max_length=150)),
                ('availability', models.BooleanField()),
                ('promotion', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.Сategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.ProductGroups')),
            ],
        ),
        migrations.AddField(
            model_name='productgroups',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.Сategory'),
        ),
    ]
