# Generated by Django 2.2.3 on 2021-01-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
