# Generated by Django 2.2.3 on 2021-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_remove_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imgPath', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
